### ISSUE TITLE
Dataset mistakes of C2C(ECCV2024)

### ISSUE THREAD

**Issue by RongchangLi** [Yanyi-Zhang/Awesome-Compositional-Zero-Shot#2]
Hello, thank you for adding our work C2C(ECCV2024). The datasets used in our work are **C-GQA** and **Sth-com** (proposed in the C2C original paper.). Could you please correct these?

**Comment by Yanyi-Zhang** [comment]
Sorry for the mistake and thanks for your impressive work. I've already fixed it!
